title: Broward GPA calculator
author: Salvador Aleguas
email: salvadoraleguas@gmail.com
description: >
  This website provides manual documentation as well as an automated calculator to calculate and/or predict your GPA. 
  Works for Cypress bay and Broward county as far as I have tested it.
  I am NOT responsible for anything that happens from these tools. Use them at your own risk.
url: "https://salvadoraleguas.info"
logo: /assets/favicon/android-chrome-512x512.png
social:
  name: saleguas
  links:
    - https://www.instagram.com/12kix/
    - https://github.com/saleguas
  
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- aboutme.html
- manual.html
- calculator.html
- advice.html

footer_icons:
- username: saleguas
  url: https://github.com/saleguas/salaleguas
  icon: icon-github.svg
- username: 12kix
  url: https://www.instagram.com/12kix/
  icon: icon-instagram.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec

baseurl: ""
